Adds the forceParams caveat.
MetaMask/json-rpc-capabilities-middleware pull request #55
Opened 2019-09-13 13:30 UTC by danjm

This PR adds a caveat that would require every call of the method to be called with only the params specified within the permission request caveat.

2019-09-13 14:24 UTC, rekmarks reviewed
Couple of stylistic edits, otherwise LGTM. That said, we should get @danfinlay's feedback as well before proceeding.

2019-09-13 14:24 UTC, rekmarks commented on README.md
> +- forceParams: Requires the method to be called exactly with a specified list of params.
I suggest we change the language to the following, as it is closer in meaning to what it actually does:
> Overwrites the params of all calls to the method with a specified list of params.

2019-09-13 14:24 UTC, rekmarks commented on src/caveats.ts
> +      req.params = [...value.params]
By convention, the caveat `value` should be the params, so L61 should be:
`req.params = [ ...value ]`

2019-09-16 22:38 UTC, danfinlay requested changes
Noticed an `.only` left in tests.

2019-09-16 22:38 UTC, danfinlay commented on test/caveats.js
> +test.only('forceParams caveat overwrites', async (t) => {
Remove `.only` clause before merging.

2019-09-17 15:01 UTC, danjm commented on test/caveats.js
> +test.only('forceParams caveat overwrites', async (t) => {
resolved with a --force push

2019-09-17 21:41 UTC, danfinlay approved these changes

2019-09-17 21:41 UTC, merged